package se.liu.kevri781;

public enum Upgrades
{
    MAX_DAMAGE, MAX_HEALTH, SPEED, JUMP_HEIGHT, ATTACK_REACH, RECOVERY_TIME, SKELETON_WARRIOR, SKELETON_SPEARMAN, SKELETON_ARCHER, LIGHTNING_MAGE, WANDERER_MAGICIAN, FIRE_WIZARD
}
